### PR TITLE
Fix for re-initializing a JSAV object

### PR DESCRIPTION
**Pull request by cashaffer**
Please check that this looks reasonable for fixing the problem with re-loading a visualization.

### CODE REVIEW

**Comment by cashaffer** [comment]
This has a problem. It works great for stand-alone AVs. But it doesn't work for OpenDSA's embedded slideshows. I haven't figured out why.

**Comment by vkaravir** [comment]
As you can see, this breaks some test cases. They seem to be related to the exercises.

Also, this will for sure break some exercises like heapsort, which adds a button inside the ```jsavcanvas``` element. This fix would also remove those buttons when initialising JSAV. Once I understand what the real issue is, I'll think about how else this could be fixed.

**Comment by cashaffer** [comment]
Yes, I think that this was way too naive.  Go ahead and delete this. :) Putting these lines in David's code solves *his* problem. But it causes lots of other problems.

**Comment by vkaravir** [comment]
Okay, closing then..

**Pull request closed without merging**
